#ifndef GUARD_EGG_HATCH_CONSTANTS_H
#define GUARD_EGG_HATCH_CONSTANTS_H

#define GFXTAG_EGG       12345
#define GFXTAG_EGG_SHARD 23456

#define PALTAG_EGG       54321

#define EGG_X (DISPLAY_WIDTH / 2)
#define EGG_Y (DISPLAY_HEIGHT / 2 - 5)

#endif // GUARD_EGG_HATCH_CONSTANTS_H
