#ifndef GUARD_EGG_HATCH_CONSTANTS_H
#define GUARD_EGG_HATCH_CONSTANTS_H

#define GFXTAG_EGG       12345
#define GFXTAG_EGG_SHARD 23456

enum PalTagsHuevos
{
    PALTAG_EGG = 54321,
    PALTAG_EGG_TIPO_1,
    PALTAG_EGG_TIPO_2,
};

#define EGG_X (DISPLAY_WIDTH / 2)
#define EGG_Y (DISPLAY_HEIGHT / 2 - 5)

#endif // GUARD_EGG_HATCH_CONSTANTS_H
