gText_AppealNumWhichMoveWillBePlayed::
	.string "¡Exhibición n.º {STR_VAR_1}!\n"
	.string "¿Qué ataque vas a usar?$"

gText_AppealNumButItCantParticipate::
	.string "¡Exhibición n.º {STR_VAR_1}!\n"
	.string "¡Pero no puede participar!$"

gText_MonAppealedWithMove::
	.string "¡{STR_VAR_1} se exhibe\n"
	.string "con {STR_VAR_2}!$"

gText_MonWasWatchingOthers::
	.string "{STR_VAR_1} estaba\n"
	.string "mirando a los otros.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_AllOutOfAppealTime::
	.string "¡Se ha acabado el tiempo\n"
	.string "de exhibición!{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"


gText_BecameMoreConsciousOfOtherMons::
	.string "Está más atento\n"
	.string "a los otros POKéMON.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonCantMakeAnAppealAfterThis::
	.string "{STR_VAR_1} no puede\n"
	.string "volver a exhibirse.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_SettledDownJustLittleBit::
	.string "Se ha relajado\n"
	.string "un poco.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_BecameObliviousToOtherMons::
	.string "Ignora la presencia\n"
	.string "de los otros POKéMON.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_BecameLessAwareOfOtherMons::
	.string "Se fija menos\n"
	.string "en los otros POKéMON.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_StoppedCaringAboutOtherMons::
	.string "Ha dejado de preocuparse\n"
	.string "por los otros POKéMON.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_TriedToStartleOtherMons::
	.string "Intentó asustar\n"
	.string "a los otros POKéMON.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_TriedToDazzleOthers::
	.string "Intentó deslumbrar\n"
	.string "a los otros POKéMON.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_JudgeLookedAwayFromMon::
	.string "El JUEZ desvió la mirada\n"
	.string "de {STR_VAR_1}.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_TriedToUnnerveNextMon::
	.string "Intentó poner nervioso\n"
	.string "al siguiente POKéMON.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonBecameNervous::
	.string "{STR_VAR_1} se ha puesto\n"
	.string "nervioso.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_AppealTriedToUnnerveWaitingMons::
	.string "Intentó intranquilizar\n"
	.string "a los POKéMON siguientes.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_TauntedMonsDoingWell::
	.string "Se burló de los que\n"
	.string "están haciéndolo bien.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonRegainedItsForm::
	.string "{STR_VAR_1} recuperó\n"
	.string "su forma.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_TriedToJamMonDoingWell::
	.string "Intentó inhibir a los que\n"
	.string "están haciéndolo bien.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_StandoutMonHustledEvenMore::
	.string "{STR_VAR_1}, ya en cabeza,\n"
	.string "destacó aún más.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_LargelyUnnoticedMonWorkedHard::
	.string "El ignorado {STR_VAR_1}\n"
	.string "se ha esforzado mucho.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_WorkedAsMuchAsMonBefore::
	.string "Se esforzó igual que\n"
	.string "los POKéMON anteriores.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealDidNotGoWell::
	.string "El ataque de {STR_VAR_1}\n"
	.string "no funcionó bien.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_WorkedAsMuchAsPrecedingMon::
	.string "Se esforzó tanto como\n"
	.string "los POKéMON anteriores.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealDidNotGoWell2::
	.string "El ataque de {STR_VAR_1}\n"
	.string "no funcionó bien.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealDidNotGoWell3::
	.string "El ataque de {STR_VAR_1}\n"
	.string "no funcionó bien.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealWentSlightlyWell::
	.string "El ataque de {STR_VAR_1}\n"
	.string "funcionó algo.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealWentPrettyWell::
	.string "El ataque de {STR_VAR_1}\n"
	.string "funcionó bastante bien.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealWentExcellently::
	.string "El ataque de {STR_VAR_1}\n"
	.string "funcionó de maravilla.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealWasDud::
	.string "El ataque de {STR_VAR_1}\n"
	.string "fue un fracaso.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealDidNotWorkVeryWell::
	.string "El ataque de {STR_VAR_1}\n"
	.string "no funcionó muy bien.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealWentSlightlyWell2::
	.string "El ataque de {STR_VAR_1}\n"
	.string "funcionó algo.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealWentPrettyWell2::
	.string "El ataque de {STR_VAR_1}\n"
	.string "funcionó bastante bien.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealWentVeryWell::
	.string "El ataque de {STR_VAR_1}\n"
	.string "funcionó muy bien.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealWentExcellently2::
	.string "El ataque de {STR_VAR_1}\n"
	.string "funcionó de maravilla.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_SameTypeAsOneBeforeGood::
	.string "El tipo es igual que el del\n"
	.string "POKéMON anterior. ¡Bien!{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_NotSameTypeAsOneBeforeGood::
	.string "Es de distinto tipo al del\n"
	.string "POKéMON anterior. ¡Bien!{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_StoodOutMuchMoreThanMonBefore::
	.string "Ha gustado mucho más que\n"
	.string "el del POKéMON anterior.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_DidntDoAsWellAsMonBefore::
	.string "No ha gustado tanto como\n"
	.string "el del POKéMON anterior.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsConditionRoseAboveUsual::
	.string "La forma de {STR_VAR_1}\n"
	.string "aumenta de forma inusual.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsHotStatusMadeGreatAppeal::
	.string "¡Gran exhibición gracias\n"
	.string "al estado de {STR_VAR_1}!{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MovedUpInLineForNextAppeal::
	.string "Se exhibirá antes\n"
	.string "en el turno siguiente.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MovedBackInLineForNextAppeal::
	.string "Se exhibirá más tarde\n"
	.string "en el turno siguiente.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_ScrambledUpOrderForNextTurn::
	.string "Ha alterado el orden\n"
	.string "del turno siguiente.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_JudgeLookedAtMonExpectantly::
	.string "El JUEZ miró a {STR_VAR_1}\n"
	.string "interesado.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_AppealComboWentOverWell::
	.string "El combo de exhibición\n"
	.string "funcionó bien.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_AppealComboWentOverVeryWell::
	.string "El combo de exhibición\n"
	.string "funcionó muy bien.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_AppealComboWentOverExcellently::
	.string "El combo de exhibición\n"
	.string "funcionó de maravilla.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonManagedToAvertGaze::
	.string "{STR_VAR_1} consiguió\n"
	.string "desviar la mirada.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonManagedToAvoidSeeingIt::
	.string "{STR_VAR_1} consiguió\n"
	.string "evitar verlo.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonIsntFazedByThatSortOfThing::
	.string "Esto no ha afectado\n"
	.string "a {STR_VAR_1}.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonBecameALittleDistracted::
	.string "{STR_VAR_1} se distrajo\n"
	.string "un poco.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_TriedToStartleOtherPokemon::
	.string "Intentó asustar\n"
	.string "a los otros POKéMON.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonLookedDownOutOfDistraction::
	.string "{STR_VAR_1} miró hacia\n"
	.string "abajo distraído.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonTurnedBackOutOfDistraction::
	.string "{STR_VAR_1} se giró\n"
	.string "distraído.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonCouldntHelpUtteringCry::
	.string "{STR_VAR_1} no pudo\n"
	.string "evitar dar un grito.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonCouldntHelpLeapingUp::
	.string "{STR_VAR_1} no pudo\n"
	.string "evitar dar un salto.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonTrippedOutOfDistraction::
	.string "{STR_VAR_1}, distraído,\n"
	.string "tropezó y se cayó.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonWasTooNervousToMove::
	.string "{STR_VAR_1} no se pudo\n"
	.string "mover de puro nervio.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_ButItMessedUp2::
	.string "Pero se hizo un lío.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_ButItFailedToMakeTargetNervous::
	.string "Pero no consiguió poner\n"
	.string "nervioso a su adversario.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_ButItFailedToMakeAnyoneNervous::
	.string "Pero no consiguió poner\n"
	.string "a nadie nervioso.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_ButItWasIgnored::
	.string "Pero fue ignorado.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_CouldntImproveItsCondition::
	.string "Pero no pudo mejorar\n"
	.string "su forma.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_BadConditionResultedInWeakAppeal::
	.string "Su exhibición fue mala\n"
	.string "debido a su baja forma.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonWasUnaffected::
	.string "{STR_VAR_1} no se vio\n"
	.string "afectado.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_RepeatedAppeal::
	.string "{STR_VAR_1} decepcionó\n"
	.string "al repetir su exhibición.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsXWentOverGreat::
	.string "{STR_VAR_3} de\n"
	.string "{STR_VAR_1} fue increíble.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsXDidntGoOverWell::
	.string "{STR_VAR_3} de\n"
	.string "{STR_VAR_1} no funcionó.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsXGotTheCrowdGoing::
	.string "¡{STR_VAR_3} de\n"
	.string "{STR_VAR_1} hizo furor!{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonCantAppealNextTurn::
	.string "{STR_VAR_1} no puede usar\n"
	.string "el próximo turno.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_AttractedCrowdsAttention::
	.string "Atrajo la atención\n"
	.string "del público.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_CrowdContinuesToWatchMon::
	.string "El público sigue\n"
	.string "observando a {STR_VAR_3}.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsMoveIsIgnored::
	.string "{STR_VAR_2} de\n"
	.string "{STR_VAR_1} fue ignorado.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_Contest_Shyness::
	.string "timidez$"

gText_Contest_Anxiety::
	.string "ansiedad$"

gText_Contest_Laziness::
	.string "pereza$"

gText_Contest_Hesitancy::
	.string "indecisión$"

gText_Contest_Fear::
	.string "miedo$"
