MoveRelearner_Text_WouldLearnNewMoves:
	.string "Hi, I'm the Move Relearner.\n"
	.string "Would you like to learn new moves?$"

MoveRelearner_Text_LevelUpMoves:
	.string "Mov. por nivel$"

MoveRelearner_Text_EggMoves:
	.string "Mov. Huevo$"

MoveRelearner_Text_TMMoves:
	.string "Mov. MT$"

MoveRelearner_Text_TutormoveMoves:
	.string "Tutor Mov.$"

MoveRelearner_Text_SeeYa:
	.string "Nos vemos!$"

MoveRelearner_Text_AnythingElse:
	.string "¿Puedo hacer algo por ti?$"

MoveRelearner_Text_ChoosePkmn:
	.string "Elige tu Pokémon.$"

MoveRelearner_Text_HaveNoPkmn:
	.string "No tienes Pokémon.$"

MoveRelearner_Text_CantTeachMoveToEgg:
	.string "Lo siento…\n"
	.string "Un huevo no puede aprender nada.$"

MoveRelearner_Text_CantTeachMoveToPkmn:
	.string "Lo siento…\p"
	.string "Parece que no hay ningún movimiento\n"
	.string "que pueda enseñarle.$"

MoveRelearner_Text_LevelUpMoveLWR::
	.string "Mov. por nivel$"

MoveRelearner_Text_EggMoveLWR::
	.string "Mov. Huevo$"

MoveRelearner_Text_TMMoveLWR::
	.string "Mov. MT$"

MoveRelearner_Text_TutorMoveLWR::
	.string "Tutor Mov.$"

MoveRelearner_Text_MoveLWR::
	.string "move$"

MoveRelearner_Text_WhichXmoveShouldTeach:
	.string "¿Qué {STR_VAR_3} debería enseñarle?$"

MoveRelearner_Text_ThankYouComeAgain:
	.string "Gracias por usar nuestros servicios.\n"
	.string "¡Vuelve pronto!$"
