gText_ObtainedTheItem::
	.string "¡Obtuvo {STR_VAR_2}!$"

gText_TheBagIsFull::
	.string "La MOCHILA está llena…$"

gText_PutItemInPocket::
	.string "{PLAYER} puso {STR_VAR_2}\n"
	.string "en el BOLSILLO de {STR_VAR_3}.$"

gText_PlayerFoundOneItem::
	.string "¡{PLAYER} encontró {STR_VAR_2}!$"

gText_TooBadBagIsFull::
	.string "¡Mala suerte!\n"
	.string "La MOCHILA está llena…$"

gText_PlayerPutItemInBag::
	.string "{PLAYER} puso {STR_VAR_2}\n"
	.string "en la MOCHILA.$"

gText_ObtainedTheDecor::
	.string "¡Obtuvo {STR_VAR_2}!$"

gText_NoRoomLeftForAnother::
	.string "¡Mala suerte! No queda sitio\n"
	.string "para {STR_VAR_2}…$"

gText_TheDecorWasTransferredToThePC::
	.string "Se envió {STR_VAR_2} al PC.$"

gText_ObtainedTheItems::
	.string "Obtuvo {STR_VAR_1} {STR_VAR_2}!$"

gText_PlayerFoundItems::
	.string "{PLAYER} encontró {STR_VAR_1} {STR_VAR_2}!$"

gText_PutCoinsAwayInCoinCase::
	.string "{PLAYER} put the COINS away in\n"
	.string "the COIN CASE.$"

gText_FoundXCoins::
	.string "{PLAYER} found\n"
	.string "{STR_VAR_1} {STR_VAR_2}!$"

gText_FoundXItems::
	.string "{PLAYER} found\n"
	.string "{STR_VAR_1} {STR_VAR_2}(s)!$"

gText_CoinCaseIsFull::
	.string "Too bad!\n"
	.string "The COIN CASE is full…$"

gText_NothingToPutThemIn::
	.string "Too bad!\n"
	.string "There's nothing to put them in…$"
