gBirchDexRatingText_AreYouCurious::
	.string "PROF. ABEDUL: ¡Ah, {PLAYER}{KUN}!\p"
	.string "¿Quieres saber cómo llevas\n"
	.string "la POKéDEX?$"

gBirchDexRatingText_Cancel::
	.string "¿Eh? Ah, ya, no has cogido\n"
	.string "bastantes POKéMON para\l"
	.string "que valga la pena…$"

gBirchDexRatingText_SoYouveSeenAndCaught::
	.string "Mmmm…\p"
	.string "Así que has visto {STR_VAR_1} POKéMON\n"
	.string "y has atrapado {STR_VAR_2} POKéMON.$"

gBirchDexRatingText_LessThan10::
	.string "Deberías ir más a las zonas de\n"
	.string "hierba alta para buscar POKéMON.$"

gBirchDexRatingText_LessThan20::
	.string "Vas cogiéndole el tranquillo, pero a\n"
	.string "partir de ahora cuesta más…$"

gBirchDexRatingText_LessThan30::
	.string "Algunos POKéMON sólo aparecen en\n"
	.string "ciertas zonas. Tienes que insistir.$"

gBirchDexRatingText_LessThan40::
	.string "Bueno, podría estar más llena, pero\n"
	.string "ya empieza a parecer una POKéDEX.$"

gBirchDexRatingText_LessThan50::
	.string "Esto va sobre ruedas.\n"
	.string "Sigue así.$"

gBirchDexRatingText_LessThan60::
	.string "¿Estás usando CAÑAS?\n"
	.string "Hay muchos POKéMON en el mar…$"

gBirchDexRatingText_LessThan70::
	.string "En vez de limitarte a atrapar\n"
	.string "POKéMON, ¿por qué no los haces\l"
	.string "evolucionar?$"

gBirchDexRatingText_LessThan80::
	.string "Esta POKéDEX va a ser fantástica.\n"
	.string "Lo presiento…$"

gBirchDexRatingText_LessThan90::
	.string "Has atrapado todos éstos…\n"
	.string "¡Tienes buena mano!$"

gBirchDexRatingText_LessThan100::
	.string "¿Has visitado la ZONA SAFARI?\p"
	.string "Dicen que hay algunos POKéMON\n"
	.string "que sólo se pueden atrapar allí.$"

gBirchDexRatingText_LessThan110::
	.string "Por fin has llegado al número 100.\n"
	.string "¡Esta POKéDEX es impresionante!$"

gBirchDexRatingText_LessThan120::
	.string "¿Sabes que se pueden encontrar\n"
	.string "ciertos POKéMON usando\l"
	.string "GOLPE ROCA?$"

gBirchDexRatingText_LessThan130::
	.string "Intercambiar POKéMON con tus\n"
	.string "amigos es una manera fácil de\l"
	.string "conseguir más.$"

gBirchDexRatingText_LessThan140::
	.string "Me han dicho que algunos POKéMON\n"
	.string "evolucionan gracias al amor que\l"
	.string "sienten por sus ENTRENADORES.$"

gBirchDexRatingText_LessThan150::
	.string "No tenía ni idea de que había\n"
	.string "tantas especies de POKéMON en\l"
	.string "HOENN.$"

gBirchDexRatingText_LessThan160::
	.string "A veces, algunos POKéMON aparecen\n"
	.string "en gran número.\p"
	.string "Es casi como una plaga, pero no hay\n"
	.string "mejor momento para atraparlos.$"

gBirchDexRatingText_LessThan170::
	.string "Mirando tu POKéDEX puedes hacerte\n"
	.string "una buena idea de los POKéMON que\l"
	.string "viven en la región de HOENN.$"

gBirchDexRatingText_LessThan180::
	.string "Yo diría que ya se te puede\n"
	.string "considerar un PROFESOR POKéMON…\l"
	.string "¡y bueno!$"

gBirchDexRatingText_LessThan190::
	.string "¡Con una POKéDEX tan completa, se\n"
	.string "puede decir que eres todo un\l"
	.string "profesional en la materia!$"

gBirchDexRatingText_LessThan200::
	.string "Estás a punto de acabar la\n"
	.string "POKéDEX.\l"
	.string "La cosa se pone emocionante.$"

gBirchDexRatingText_DexCompleted::
	.string "¡Felicidades!\n"
	.string "¡Tu POKéDEX está completa!$"

gBirchDexRatingText_OnANationwideBasis::
	.string "Mmmm…\n"
	.string "A escala nacional…\p"
	.string "has visto {STR_VAR_1} POKéMON y\n"
	.string "has atrapado {STR_VAR_2} POKéMON.$"

@ FRLG

PokedexRating_Text_HowIsPokedexComingAlong::
	.string "OAK: Good to see you!\n"
	.string "How is your POKéDEX coming along?\p"
	.string "Here, let me take a look.$"

PokedexRating_Text_SeenXOwnedY::
	.string "The amount of progress you've made\n"
	.string "on your POKéDEX is:\p"
	.string "{STR_VAR_1} POKéMON seen and\n"
	.string "{STR_VAR_2} POKéMON owned.\p"
	.string "{FONT_NORMAL}PROF. OAK's rating:$"

PokedexRating_Text_LessThan10::
	.string "You still have lots to do.\p"
	.string "Go into every patch of grass you\n"
	.string "see and look for POKéMON!$"

PokedexRating_Text_LessThan20::
	.string "It looks as if you're getting on\n"
	.string "the right track!\p"
	.string "I've given one of my AIDES a FLASH\n"
	.string "HM. Make sure you go get it!$"

PokedexRating_Text_LessThan30::
	.string "Your POKéDEX could use a bit more\n"
	.string "volume still!\p"
	.string "Try to catch other species of\n"
	.string "POKéMON!$"

PokedexRating_Text_LessThan40::
	.string "Good, it's apparent that you're\n"
	.string "trying hard!\p"
	.string "I've given one of my AIDES an\n"
	.string "ITEMFINDER. Be sure to collect it!$"

PokedexRating_Text_LessThan50::
	.string "Your POKéDEX is coming along quite\n"
	.string "well!\p"
	.string "I've given one of my AIDES an\n"
	.string "AMULET COIN. Be sure to get it!$"

PokedexRating_Text_LessThan60::
	.string "Ah, you've finally topped 50\n"
	.string "species!\p"
	.string "I've given one of my AIDES an EXP.\n"
	.string "SHARE. Be sure to go get it!$"

PokedexRating_Text_LessThan70::
	.string "Hoho! This is turning into quite the\n"
	.string "respectable POKéDEX!$"

PokedexRating_Text_LessThan80::
	.string "Very good!\p"
	.string "I think you'll collect even more\n"
	.string "POKéMON by going fishing!$"

PokedexRating_Text_LessThan90::
	.string "Wonderful! Let me guess… You\n"
	.string "like to collect things, don't you?$"

PokedexRating_Text_LessThan100::
	.string "I'm impressed!\n"
	.string "It must have been difficult to do!$"

PokedexRating_Text_LessThan110::
	.string "You've finally hit 100 species!\n"
	.string "I can't believe how good you are!$"

PokedexRating_Text_LessThan120::
	.string "You even have the evolved forms\n"
	.string "of POKéMON! Super!$"

PokedexRating_Text_LessThan130::
	.string "Excellent! Trade with friends to\n"
	.string "get some more!$"

PokedexRating_Text_LessThan140::
	.string "Outstanding!\n"
	.string "You've become a real pro at this!$"

PokedexRating_Text_LessThan150::
	.string "I have nothing left to say!\n"
	.string "You're the POKéMON PROFESSOR now!$"

PokedexRating_Text_Complete::
	.string "Your POKéDEX is entirely complete!\n"
	.string "Congratulations!!$"

PokedexRating_Text_NationalDexSeenXOwnedY::
	.string "And your NATIONAL POKéDEX is:\p"
	.string "{STR_VAR_1} POKéMON seen and\n"
	.string "{STR_VAR_2} POKéMON owned.$"

PokedexRating_Text_LookForwardToFilledNationalDex::
	.string "I'll be looking forward to seeing\n"
	.string "you fill the NATIONAL POKéDEX!$"

PokedexRating_Text_YouveCompletedDex::
	.string "Finally…\p"
	.string "You've finally completed the\n"
	.string "POKéDEX!\p"
	.string "It's magnificent!\n"
	.string "Truly, this is a fantastic feat!$"

PokedexRating_Text_Wroooaaarrr::
	.string "Wroooooooaaaaaarrrr!$"

PokedexRating_Text_ThankYouMadeDreamReality::
	.string "Thank you, {PLAYER}!\n"
	.string "Sincerely, thank you!\l"
	.string "You've made my dream a reality!$"

PokedexRating_Text_LoveSeeingYourPokedex::
	.string "OAK: Ah, welcome!\p"
	.string "Tell me, how is your POKéDEX\n"
	.string "coming along?\p"
	.string "Wahaha!\p"
	.string "Actually, I know how it is, but I\n"
	.string "love seeing it anyway!\p"
	.string "Let's see…$"
