	.align 2
gText_ConfirmSave::
	.string "Quieres guardar la partida?$"

gText_AlreadySavedFile::
	.string "Ya hay una partida guardada.\n"
	.string "Quieres sobreescribirla?$"

gText_SavingDontTurnOff::
	.string "Guardando…\n"
	.string "No apagues la consola.$"

gText_PlayerSavedGame::
	.string "{PLAYER} guardó la partida.$"

gText_DifferentSaveFile::
	.string "WARNING!\p"
	.string "There is a different game file that\n"
	.string "is already saved.\p"
	.string "If you save now, the other file's\n"
	.string "adventure, including items and\l"
	.string "POKéMON, will be entirely lost.\p"
	.string "Are you sure you want to save now\n"
	.string "and overwrite the other save file?$"

gText_SaveError::
	.string "Save error.\p"
	.string "Please exchange the\n"
	.string "backup memory.$"

gText_SavingDontTurnOffPower::
	.string "GUARDANDO…\n"
	.string "NO APAGUES LA CONSOLA.$"
