Route111_OldLadysRestStop_MapScripts::
	map_script MAP_SCRIPT_ON_TRANSITION, Route111_OldLadysRestStop_OnTransition
	.byte 0

Route111_OldLadysRestStop_OnTransition:
	setflag FLAG_LANDMARK_OLD_LADY_REST_SHOP
	end

Route111_OldLadysRestStop_EventScript_OldLady::
	lock
	faceplayer
	msgbox Route111_OldLadysRestStop_Text_RestUpHere, MSGBOX_YESNO
	goto_if_eq VAR_RESULT, YES, Route111_OldLadysRestStop_EventScript_Rest
	goto_if_eq VAR_RESULT, NO, Route111_OldLadysRestStop_EventScript_DeclineRest
	end

Route111_OldLadysRestStop_EventScript_Rest::
	msgbox Route111_OldLadysRestStop_Text_TakeYourTimeRestUp, MSGBOX_DEFAULT
	closemessage
	call Common_EventScript_OutOfCenterPartyHeal
	msgbox Route111_OldLadysRestStop_Text_StillTiredTakeAnotherRest, MSGBOX_YESNO
	goto_if_eq VAR_RESULT, YES, Route111_OldLadysRestStop_EventScript_Rest
	goto_if_eq VAR_RESULT, NO, Route111_OldLadysRestStop_EventScript_DeclineRest
	end

Route111_OldLadysRestStop_EventScript_DeclineRest::
	msgbox Route111_OldLadysRestStop_Text_DontNeedToBeShy, MSGBOX_DEFAULT
	release
	end

Route111_OldLadysRestStop_Text_RestUpHere:
	.string "Ay, ay, ay…\n"
	.string "Tus POKéMON parecen agotados…\p"
	.string "¿Por qué no descansas aquí?\n"
	.string "Es lo mejor que puedes hacer, en serio.$"

Route111_OldLadysRestStop_Text_TakeYourTimeRestUp:
	.string "Exacto.\n"
	.string "Tómate tu tiempo y descansa.$"

Route111_OldLadysRestStop_Text_StillTiredTakeAnotherRest:
	.string "Ay, ay, ay…\n"
	.string "Tus POKéMON siguen hechos polvo…\p"
	.string "¿Por qué no vuelves a descansar aquí?\n"
	.string "Es lo mejor que puedes hacer, en serio.$"

Route111_OldLadysRestStop_Text_DontNeedToBeShy:
	.string "¿Seguro?\n"
	.string "Yo que tú me lo pensaría dos veces…$"

